{"uuid":"334e8d59-a4cf-4080-a032-316dee829f4d","historyId":"61f072610383f638e96b0111122d2ced","fullName":"com.ex_3_Selenium_Locator.Task_28_day_Mini_Project.test_vwo_trial_login_invalid_login","labels":[{"name":"package","value":"com.ex_3_Selenium_Locator.Task_28_day_Mini_Project"},{"name":"testClass","value":"com.ex_3_Selenium_Locator.Task_28_day_Mini_Project"},{"name":"testMethod","value":"test_vwo_trial_login_invalid_login"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"LearningSeleniumATB13x"},{"name":"subSuite","value":"com.ex_3_Selenium_Locator.Task_28_day_Mini_Project"},{"name":"host","value":"DESKTOP-6EE2PGK"},{"name":"thread","value":"7728@DESKTOP-6EE2PGK.main(3)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Abhishek Mahajan"}],"links":[],"name":"test_vwo_trial_login_invalid_login","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Error message is not displayed! expected [true] but found [false]","trace":"java.lang.AssertionError: Error message is not displayed! expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat com.ex_3_Selenium_Locator.Task_28_day_Mini_Project.test_vwo_trial_login_invalid_login(Task_28_day_Mini_Project.java:69)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:565)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1604)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"TC#1 - Verify that with invalid login for free trial, error message is displayed!","steps":[],"attachments":[],"parameters":[],"start":1756401698051,"stop":1756401718499}